project_id = "swvvyxuozwqvyaberqvu"

[functions.server]
verify_jwt = false

[functions.index-knowledge]
enabled = true
verify_jwt = true
import_map = "./functions/index-knowledge/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/index-knowledge/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/index-knowledge/*.html" ]
